### ISSUE TITLE
L1Escrow will use protocolDAI for withdraw before withdrawing from sDAI 

### ISSUE THREAD

**Issue by oneski** [pyk/zkevm-dai#1]
https://github.com/pyk/zkevm-dai/blob/965e1696e612edf8b8d97c289b24da3b4a32183e/src/L1Escrow.sol#L229

protocolDAI should only change during rebalance()
withdraws should always come from sDAI reserves

**Comment by oneski** [comment]
logic should be
-withdraw from sDAI first
if no sDAI then uses DAI in the L1_Escrow

(basically protocolDAI gets used last)

**Comment by pyk** [comment]
@oneski noted. I've updated the logic
